/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AMAZON_BEDROCK_ACCESS_KEY_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AMAZON_BEDROCK_REGION": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AMAZON_BEDROCK_SECRET_ACCESS_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AMAZON_BEDROCK_SESSION_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ANTHROPIC_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "APIFY_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ASSEMBLYAI_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AZURE_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AZURE_RESOURCE_NAME": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AppDownloadsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "BETTER_AUTH_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CEREBRAS_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "COHERE_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CallRecordingTranscribeQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "CallRecordingTranscribeQueueDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "CallRecordingsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "DB_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DEEP_INFRA_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DEEP_SEEK_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DocsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "DocumentExtractionQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "DocumentExtractionQueueDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "EMAIL_FROM": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "EMAIL_FROM_INVITATION": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "EMAIL_FROM_SUPPORT": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AirFrameRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "AirFrameWeb": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "EmbeddingsQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "EmbeddingsQueueDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "EvalQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "EvalQueueDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "FAL_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FIREWORKS_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_GENERATIVE_AI_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_VERTEX_CLIENT_EMAIL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_VERTEX_PRIVATE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GRAPHDB_PASSWORD": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GRAPHDB_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GRAPHDB_USERNAME": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GROQ_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "HUBSPOT_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "HUBSPOT_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "JINA_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "KnowledgeGraphQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "KnowledgeGraphQueueDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "MARKITDOWN_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MISTRAL_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MarkItDownApi": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "OPENAI_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OcrQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "OcrQueueDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "PERPLEXITY_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "QDRANT_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "QDRANT_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "RESEND_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "S3BucketQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "S3BucketQueueDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "SPEECHMATICS_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SPEECHMATICS_CALLBACK_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SmallTaskQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "SmallTaskQueueDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "SpeechmaticsCallback": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "TAVILY_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TOGETHER_AI_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TrainingMaterialsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "XAI_GROK_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}