# Automatically generated by SST
# pylint: disable=all
from typing import Any

class Resource:
    class App:
        name: str
        stage: str
    class BETTER_AUTH_SECRET:
        type: str
        value: str
    class DB_URL:
        type: str
        value: str
    class DocumentProcessingQueue:
        type: str
        url: str
    class OPENAI_API_KEY:
        type: str
        value: str
    class RESEND_API_KEY:
        type: str
        value: str
    class ServiceDocumentsBucket:
        name: str
        type: str
    class StarterWeb:
        type: str
        url: str

