"""Constants for service document generation - machine types, problems, solutions, and parts."""

MACHINE_CATEGORIES = {
	"Ovens": {
		"models": [
			"ConvectionPro 5000",
			"RapidBake 3000",
			"TurboHeat X-200",
			"CombiSteam Elite",
			"DeckMaster 480",
		],
		"common_problems": [
			"Temperature not reaching setpoint",
			"Uneven heating distribution across cooking zones",
			"Door seal leaking heat and steam",
			"Ignition system failure - burners not lighting",
			"Convection fan motor making grinding noise",
			"Control panel not responding to input",
			"Timer malfunction - not counting down properly",
			"Oven overheating beyond set temperature",
			"Pilot light extinguishing during operation",
			"Stone deck cracking from thermal stress",
		],
		"solutions": [
			"Replaced thermocouple sensor and recalibrated temperature controller",
			"Calibrated temperature controller and tested all zones",
			"Installed new high-temperature door gasket and adjusted door alignment",
			"Replaced igniter assembly and cleaned gas valve",
			"Replaced convection fan motor and lubricated bearings",
			"Reflashed control board firmware to latest version",
			"Replaced timer relay and tested countdown function",
			"Adjusted high limit thermostat and replaced safety switch",
			"Cleaned pilot assembly and replaced thermocouple",
			"Inspected deck for damage and adjusted temperature ramp settings",
		],
		"parts": [
			"Thermocouple Type K 24-inch",
			"Door gasket 24x30 high-temp",
			"Igniter element hot surface",
			"Convection fan motor 1/4 HP 120V",
			"Control board PCB-5000",
			"Timer relay 120V DPDT",
			"High limit thermostat 550F",
			"Pilot assembly with thermocouple",
			"Gas valve safety solenoid",
			"Temperature probe RTD",
		],
	},
	"Fryers": {
		"models": [
			"DeepFry Pro 450",
			"TurboCrisp 2000",
			"OilGuard Elite",
			"FryMaster XL-4000",
			"CrispKing 300",
		],
		"common_problems": [
			"Oil not heating to temperature setpoint",
			"High limit switch tripping repeatedly",
			"Gas valve not opening during heat cycle",
			"Burner flame irregular or yellow",
			"Oil filtration system clogged with debris",
			"Temperature probe reading 50 degrees low",
			"Basket lift mechanism stuck in up position",
			"Oil overflowing from vat during operation",
			"Thermostat cycling too frequently",
			"Heating elements failing to energize",
		],
		"solutions": [
			"Replaced heating element and tested temperature rise",
			"Adjusted high limit switch setting and cleaned sensor probe",
			"Replaced gas valve solenoid and tested safety lockout",
			"Cleaned burner orifices and adjusted air mixture for blue flame",
			"Replaced filter pump motor and cleaned all filter lines",
			"Installed new temperature probe and calibrated controller",
			"Lubricated lift mechanism and replaced worn cable assembly",
			"Adjusted oil level sensor and cleared drain obstruction",
			"Replaced thermostat and adjusted differential settings",
			"Tested contactor and replaced heating element assembly",
		],
		"parts": [
			"Heating element 208V 15kW",
			"High limit switch 450F auto-reset",
			"Gas valve solenoid 24V",
			"Burner orifice set natural gas",
			"Filter pump motor 1/3 HP",
			"Temperature probe RTD 12-inch",
			"Basket lift cable assembly stainless",
			"Oil level sensor float switch",
			"Thermostat 200-400F",
			"Contactor 30A 240V",
		],
	},
	"Mixers": {
		"models": [
			"PlanetaryMix 60",
			"DoughMaster 80Q",
			"SpiralPro 120",
			"VersaMix 40",
			"HeavyDuty 100",
		],
		"common_problems": [
			"Motor overheating during normal operation",
			"Gearbox making loud grinding noise under load",
			"Speed control not responding to adjustments",
			"Bowl not locking properly in position",
			"Planetary gear slipping during mixing",
			"Safety interlock malfunction - unit runs with guard up",
			"Attachment hub worn and wobbling",
			"Motor starting sluggishly or failing to start",
			"Excessive vibration during operation",
			"Transmission oil leaking from gearbox",
		],
		"solutions": [
			"Replaced motor brushes and cleaned cooling fan intake",
			"Rebuilt gearbox with new bearings and fresh lubricant",
			"Replaced speed controller PCB and calibrated speed range",
			"Adjusted bowl lock mechanism and replaced worn pin",
			"Replaced planetary gear assembly and ring gear",
			"Replaced safety microswitch and adjusted guard alignment",
			"Machined and fitted new hub bushing",
			"Replaced motor start capacitor and tested startup current",
			"Balanced mixing attachments and tightened motor mount bolts",
			"Replaced gearbox seal and refilled with proper transmission oil",
		],
		"parts": [
			"Motor brush set carbon",
			"Bearing kit upper and lower",
			"Speed control board digital",
			"Bowl lock pin stainless",
			"Planetary gear set hardened",
			"Safety microswitch 15A",
			"Hub bushing bronze",
			"Start capacitor 88-108 MFD",
			"Motor mount isolator rubber",
			"Gearbox seal kit",
		],
	},
	"Refrigeration": {
		"models": [
			"ChillMaster 2000",
			"WalkIn Pro Series",
			"ReachIn Elite 3-Door",
			"UndercounterCool 48",
			"DisplayCase Premium",
		],
		"common_problems": [
			"Compressor not running - no cooling",
			"Temperature fluctuating outside acceptable range",
			"Frost buildup on evaporator coils",
			"Condenser fan not operating",
			"Door not sealing properly - warm air infiltration",
			"Refrigerant leak detected at service valve",
			"Defrost timer malfunction - continuous run",
			"Condensate drain line frozen and backing up",
			"Evaporator fan motor seized",
			"Compressor short cycling every few minutes",
		],
		"solutions": [
			"Replaced compressor start relay and run capacitor",
			"Recharged refrigerant to proper subcooling and adjusted TXV",
			"Replaced defrost heater and timer, tested full defrost cycle",
			"Replaced condenser fan motor and cleaned condenser coils",
			"Installed new door gasket and adjusted door hinges",
			"Repaired leak with silver solder, evacuated and recharged system",
			"Replaced defrost timer and tested all cycle modes",
			"Cleared drain line with hot water and installed drain heater",
			"Replaced evaporator fan motor and checked blade clearance",
			"Diagnosed and replaced faulty start capacitor, checked pressures",
		],
		"parts": [
			"Start relay and run capacitor kit",
			"R-404A refrigerant 2 lbs",
			"Defrost heater 1200W 240V",
			"Condenser fan motor 1/6 HP",
			"Door gasket 36x78 magnetic",
			"TXV valve R-404A 1/2 ton",
			"Defrost timer 120V 6-hour cycle",
			"Drain heater 120V 80W",
			"Evaporator fan motor 1/20 HP",
			"Compressor start capacitor 88-108 MFD",
		],
	},
	"Dishwashers": {
		"models": [
			"SaniSpray 3000",
			"RackMaster Conveyor",
			"UndercounterClean Pro",
			"DoorType HT-60",
			"FlightType Industrial",
		],
		"common_problems": [
			"Water not heating to proper sanitizing temperature",
			"Wash pump not operating - no spray pressure",
			"Door solenoid leaking water during cycle",
			"Spray arms not rotating during wash",
			"Detergent dispenser clogged and not dispensing",
			"Drain pump failure - water standing in tank",
			"Chemical pump not priming - no rinse aid",
			"Cycle not advancing - stuck in wash mode",
			"Steam hood exhaust fan not running",
			"Tank fill valve stuck open - continuous overflow",
		],
		"solutions": [
			"Replaced booster heater element and tested temperature rise",
			"Replaced wash pump motor and impeller assembly",
			"Installed new door solenoid valve and adjusted door alignment",
			"Cleaned spray arm bearings and replaced upper arm",
			"Disassembled and cleaned dispenser, replaced check valve",
			"Replaced drain pump and cleared obstruction from sump",
			"Replaced chemical pump and primed system with rinse aid",
			"Replaced cycle controller and tested all cycle functions",
			"Replaced exhaust fan motor and cleaned ductwork",
			"Replaced fill valve and adjusted water level sensor",
		],
		"parts": [
			"Booster heater 240V 6kW",
			"Wash pump motor 3/4 HP",
			"Door solenoid 120V 3/4-inch",
			"Spray arm bearing set UHMW",
			"Dispenser assembly complete",
			"Drain pump 1/2 HP 120V",
			"Chemical pump 24V peristaltic",
			"Cycle controller electronic",
			"Exhaust fan motor 1/3 HP",
			"Fill valve 3/4-inch 120V",
		],
	},
	"Griddles": {
		"models": [
			"FlatTop Pro 48",
			"ElectricGrill 36",
			"GasGriddle HeavyDuty",
			"ChromeTop Elite",
			"ThermoStatic 60",
		],
		"common_problems": [
			"Uneven heating across griddle surface",
			"Thermostat not maintaining set temperature",
			"Gas burners not igniting properly",
			"Griddle top warped from thermal stress",
			"Grease trap overflowing during service",
			"Control knobs loose or broken off",
			"Pilot light keeps going out",
			"Cold spots on cooking surface",
			"Standing pilot wasting gas continuously",
			"Griddle plate surface pitting and flaking",
		],
		"solutions": [
			"Replaced heating elements in cold zones and tested distribution",
			"Replaced thermostat and calibrated to accurate temperature",
			"Cleaned burners and replaced spark igniter module",
			"Resurfaced griddle top with grinding and re-seasoning",
			"Cleaned grease trap and adjusted griddle slope for drainage",
			"Replaced control valve stems and knobs",
			"Replaced thermocouple and cleaned pilot assembly",
			"Adjusted burner manifold pressure and tested all zones",
			"Converted to electronic ignition system",
			"Refinished griddle plate and applied protective coating",
		],
		"parts": [
			"Heating element 208V 5kW",
			"Thermostat 200-450F snap-action",
			"Spark igniter module 120V",
			"Griddle plate 48x24 3/4-inch steel",
			"Grease tray assembly stainless",
			"Control valve stem with knob",
			"Thermocouple 24-inch heavy-duty",
			"Burner manifold pressure regulator",
			"Electronic ignition control board",
			"Griddle seasoning and conditioning kit",
		],
	},
}

TECHNICIANS = [
	{"name": "Mike Johnson", "id": "TECH-001", "cert": "EPA Universal Certified"},
	{"name": "Sarah Williams", "id": "TECH-015", "cert": "CFESA Certified Master"},
	{"name": "Carlos Rodriguez", "id": "TECH-008", "cert": "Master Technician Level 3"},
	{"name": "Jennifer Kim", "id": "TECH-023", "cert": "CFESA Level II Certified"},
	{"name": "David Chen", "id": "TECH-012", "cert": "EPA Type I/II Certified"},
	{"name": "Amanda Foster", "id": "TECH-019", "cert": "Factory Certified Specialist"},
	{"name": "Robert Taylor", "id": "TECH-005", "cert": "Senior Field Technician"},
	{"name": "Lisa Martinez", "id": "TECH-031", "cert": "CFESA Certified Specialist"},
]

COMPANIES = [
	"Restaurant Equipment Services LLC",
	"Commercial Kitchen Solutions Inc",
	"FoodService Tech Pros",
	"National Restaurant Repair",
	"Metro Kitchen Equipment Service",
	"Professional Food Equipment Co",
]
